### ISSUE TITLE
calc_var.py: Dealing with extended columns

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/Robbie#12]
calc_var.py is currently unable to deal with extended columns. 

```
WARNING: Using non-standard extended column convention
WARNING: Other FITS software may not see columns 999-1620
./calc_var.py --infile GRB180805A_28s_flux_table.fits --outfile GRB180805A_28s_flux_table_var.fits
./plot_lc.py GRB180805A_28s_flux_table_var.fits
Traceback (most recent call last):
  File "./calc_var.py", line 132, in <module>
    df = load_corrected_table(results.infile)
  File "./calc_var.py", line 63, in load_corrected_table
    df = tab.to_pandas()
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/table/table.py", line 2690, in to_pandas
    raise ValueError("Cannot convert a table with multi-dimensional columns to a pandas DataFrame")
ValueError: Cannot convert a table with multi-dimensional columns to a pandas DataFrame
loading GRB180805A_28s_flux_table_var.fits
Traceback (most recent call last):
  File "./plot_lc.py", line 46, in <module>
    cat = Table.read(fname).to_pandas()
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/table/table.py", line 2521, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/registry.py", line 516, in read
    fileobj = ctx.__enter__()
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/utils/data.py", line 206, in get_readable_fileobj
    fileobj = open(name_or_obj, 'rb')
IOError: [Errno 2] No such file or directory: 'GRB180805A_28s_flux_table_var.fits'
Makefile:143: recipe for target 'GRB180805A_28s_flux_table_var.fits' failed
make: *** [GRB180805A_28s_flux_table_var.fits] Error 1
```

**Comment by PaulHancock** [comment]
This is a fundamental limitation of fits files, only 1000 columns can be written to the fits file.
TOPCAT has a fancy way of cramming the additional columns into the 1000th column, but this isn't recognised by astorpy. 

Possible solutions:
- cut the number of columns that are preserved (though eventually 1000 epochs will still trigger this problem)
- use a different file format (hdf5 or votables will both work, though stilts doesn't support hdf5)

**Comment by PaulHancock** [comment]
Temporary fix by using votable format. It is slower to read/write than fits but at least it works for now.

**Comment by PaulHancock** [comment]
Temporary fix has been upgraded to permanent fix.
