### ISSUE TITLE
Image argument list too long to create an image cube

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/Robbie#13]
I am trying to run Robbie on 3315 images (there are 221 0.5s images in my 15 2-minute snapshots). I received the following error:

```
make: execvp: /bin/bash: Argument list too long
Makefile:131: recipe for target 'GRB180805A_05s_cube.fits' failed
make: *** [GRB180805A_05s_cube.fits] Error 127

```

**Comment by PaulHancock** [comment]
Cause of the error: 3315 arguments on the command line is too long for bash to handle.

This instance of the error is fixed, but I suspect there are more down the line that will come up.

**Comment by PaulHancock** [comment]
The next likely problem will be joining the 3315 different tables together.

I suspect that a database solution may be better -> we have uuids which can act as keys to join tables/epochs. This will mean that we need to adjust the plotting codes, but could remove our dependency on topcat.

Agregate functions could also mean that we no longer need to use pandas...

**Comment by gemmaanderson** [comment]
Following the update of make_cube.py, I am now getting the following errors listed below. Your commit for make_cube.py says "make cube from warped images instead of base images", however, I do not run fits_warp on the 0.5s images (since there are 3315 of them and there is unlikely to be bright enough sources for matching)

```
sed -e 's:.fits:_warped.fits:g' all_images_180805a_05s.txt > temp_list.txt
./make_cube.py --out GRB180805A_05s_cube.fits --infile temp_list.txt
rm temp_list.txt
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
Traceback (most recent call last):
  File "./make_cube.py", line 63, in <module>
    stack(files=files, out=results.outfile)
  File "./make_cube.py", line 26, in stack
    dtype=np.float32)
MemoryError
./make_mean.py GRB180805A_05s_cube.fits GRB180805A_05s_mean.fits
reading GRB180805A_05s_cube.fits
Traceback (most recent call last):
  File "./make_mean.py", line 44, in <module>
    mean(infile, out=outfile)
  File "./make_mean.py", line 24, in mean
    hdu = fits.open(cube)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 399, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 987, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/fits/util.py", line 395, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: 'GRB180805A_05s_cube.fits'
Makefile:139: recipe for target 'GRB180805A_05s_mean.fits' failed
make: *** [GRB180805A_05s_mean.fits] Error 1
```

**Comment by PaulHancock** [comment]
I have changed the way that the mean image is created, and how the various catalogues are combined and confirm that this issue is now fixed for 25 epochs.

I'd like to see a test on a large number of epochs to confirm that there is not another version of this problem.

**Comment by gemmaanderson** [comment]
I've made it to the next bug! See the following error message - 

```
aegean:INFO found 3493 sources total
catalogs:INFO wrote GRB180805A_05s_mean_comp.fits
catalogs:INFO wrote GRB180805A_05s_mean_isle.fits
catalogs:INFO wrote GRB180805A_05s_mean_comp.reg
catalogs:INFO wrote GRB180805A_05s_mean_isle.reg
if [[ -n "monitor_grb180805a_05s.fits" ]] ;\
then java -jar /home/gemma/software/stilts.jar tcatn nin=2 in1=GRB180805A_05s_mean_comp.fits in2=monitor_grb180805a_05s.fits out=GRB180805A_05s_persistent_sources.fits\
else cp GRB180805A_05s_mean_comp.fits GRB180805A_05s_persistent_sources.fits ;\
fi

Unused arguments: cp GRB180805A_05s_mean_comp.fits GRB180805A_05s_persistent_sources.fits

Usage: tcatn nin=<count> ifmtN=<in-format> inN=<tableN> icmdN=<cmds>
             ocmd=<cmds>
             omode=out|meta|stats|count|cgi|discard|topcat|samp|plastic|tosql|gui
             out=<out-table> ofmt=<out-format> seqcol=<colname>
             loccol=<colname> uloccol=<colname> countrows=true|false

Makefile:157: recipe for target 'GRB180805A_05s_persistent_sources.fits' failed
make: *** [GRB180805A_05s_persistent_sources.fits] Error 1
```

**Comment by PaulHancock** [comment]
Commit c9b47df should fix this typo.

**Comment by gemmaanderson** [comment]
Still an error message

```
if [[ -n "monitor_grb180805a_05s.fits" ]] ;\
then java -jar /home/gemma/software/stilts.jar tcatn nin=2 in1=GRB180805A_05s_mean_comp.fits in2=monitor_grb180805a_05s.fits out=GRB180805A_05s_persistent_sources.fits ;\
else cp GRB180805A_05s_mean_comp.fits GRB180805A_05s_persistent_sources.fits ;\
fi
Error: Column type mismatch (island(Short) not compatible with island(Integer))
Makefile:157: recipe for target 'GRB180805A_05s_persistent_sources.fits' failed
make: *** [GRB180805A_05s_persistent_sources.fits] Error 1
```

**Comment by gemmaanderson** [comment]
```
if [[ -n "monitor_grb180805a_05s.csv" ]] ;\
then java -jar /home/gemma/software/stilts.jar tcatn nin=2 in1=GRB180805A_05s_mean_comp.fits in2=monitor_grb180805a_05s.csv out=GRB180805A_05s_persistent_sources.fits ;\
else cp GRB180805A_05s_mean_comp.fits GRB180805A_05s_persistent_sources.fits ;\
fi
Error: Can't make StarTable from "monitor_grb180805a_05s.csv" (tried FITS-plus, colfits-plus, colfits-basic, FITS, VOTable, CDF, GBIN)
Makefile:157: recipe for target 'GRB180805A_05s_persistent_sources.fits' failed
make: *** [GRB180805A_05s_persistent_sources.fits] Error 1
```

**Comment by gemmaanderson** [comment]
There is now a similar problem with the database:

```
./remake_db.py --name GRB180805A_05s_flux_table.db ;\
for f in ${files[@]} ;\
do im=$(echo ${f} | sed -e 's:_prior_comp.fits:.fits:g') ;\
./add_cat_to_db.py --name GRB180805A_05s_flux_table.db --cat ${f} --image ${im};\
done
./calc_var.py --name GRB180805A_05s_flux_table.db
make: execvp: /bin/bash: Argument list too long
Makefile:171: recipe for target 'GRB180805A_05s_flux_table.db' failed
make: *** [GRB180805A_05s_flux_table.db] Error 127

```

**Comment by PaulHancock** [comment]
I believe that this is fixed as at 633998a
This works for ~25 epochs, need you to test it again for ~3k epochs.

**Comment by gemmaanderson** [comment]
I have hit another error. It finished making all the variable light curves but seems to have stopped partway through making the variables.png plot:

```

plots/ffd360dd-854e-4703-acee-9a598eea3d77.png ... done
AeRes -c GRB180805A_05s_mean_comp.fits -f GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped.fits -r GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.fits --mask --sigma=0.1
8821:INFO This is AeRes v0.2.5-(2017-05-12)
8821:INFO Using GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped.fits and GRB180805A_05s_mean_comp.fits to make GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.fits
8821:INFO Reading file GRB180805A_05s_mean_comp.fits
8821:INFO read 1765 sources from GRB180805A_05s_mean_comp.fits
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
8821:WARNING VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
8821:INFO modeled 1765 sources
8821:INFO wrote residual to GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.fits
aegean GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.fits --background GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_bkg.fits --noise GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_rms.fits \
--table GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.fits,GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked.reg --island --region cutout_big_v4.min
aegean:INFO This is Aegean 2.0.2-(2018-07-19)
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
logger:WARNING VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
aegean:INFO Found 8 cores
aegean:INFO Using 8 cores
aegean:ERROR Region file {0} not found
Makefile:194: recipe for target 'GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked_comp.fits' failed
make: *** [GRB180805A/05s_images/regrid_1217495184-0.5s-t8-9-pbcorr-I_warped_blanked_comp.fits] Error 1

```

**Comment by PaulHancock** [comment]
It looks like you have a typo in the region file name:
you have `cutout_big_v4.min` but it should probably be `cutout_big_v4.mim`

**Comment by gemmaanderson** [comment]
Next long list issue:

```
if [[ -z ${files} ]];\
  then touch GRB180805A_05s_transients.fits;\
else \
  cmd="java -jar /home/gemma/software/topcat-full.jar -stilts tcatn nin=${#files[@]}" ;\
  for i in $( seq 1 1 ${#files[@]} ) ;\
  do \
    j=$( echo "${i} -1" | bc ) ;\
    cmd="${cmd} in${i}=${files[${j}]} icmd${i}='addcol epoch ${i}'" ;\
  done ;\
  cmd="${cmd} out=GRB180805A_05s_transients.fits ofmt=fits" ;\
  echo ${cmd} | bash ;\
fi
make: execvp: /bin/bash: Argument list too long
Makefile:211: recipe for target 'GRB180805A_05s_transients.fits' failed
make: *** [GRB180805A_05s_transients.fits] Error 127

```

**Comment by PaulHancock** [comment]
As of b04f49a I have replaced this call to stilts with a python call which should avoid the very long argument list.

**Comment by gemmaanderson** [comment]
Error:
```

./plot_transients.py --in GRB180805A_05s_transients.fits --plot GRB180805A_05s_transients.png
Traceback (most recent call last):
  File "./plot_transients.py", line 71, in <module>
    grain_plot(fitsfile=results.infile, plotfile=results.plotfile)
  File "./plot_transients.py", line 20, in grain_plot
    nepochs = np.max(tab['epoch'])*1.
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/table/table.py", line 1222, in __getitem__
    return self.columns[item]
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/table/table.py", line 109, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'epoch'
Makefile:220: recipe for target 'GRB180805A_05s_transients.png' failed
make: *** [GRB180805A_05s_transients.png] Error 1

```

**Comment by PaulHancock** [comment]
This is for the `make` version of Robbie which is no longer being developed.
