### ISSUE TITLE
fits_warp error in Robbie

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/Robbie#16]
I rerunning Robbie on new 28s images and I have turned fits_warp back on. 
fits_warp is giving me the following error:

```
aegean:INFO found 399 sources total
catalogs:INFO wrote GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_comp.fits
catalogs:INFO wrote GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_isle.fits
catalogs:INFO wrote GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_comp.reg
catalogs:INFO wrote GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_isle.reg
if [[ -n "" ]] ;\
then touch GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_xm.fits ;\
else ./fits_warp.py --refcat GRB180805A_28s_refcat.fits --incat GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_comp.fits --xm GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_xm.fits ;\
fi
Traceback (most recent call last):
  File "./fits_warp.py", line 464, in <module>
    radius=2./3/60)
  File "./fits_warp.py", line 333, in warped_xmatch
    refcat = Table.read(refcat)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/table/table.py", line 2521, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/registry.py", line 528, in read
    'read', cls, path, fileobj, args, kwargs)
  File "/home/gemma/pytrans/local/lib/python2.7/site-packages/astropy/io/registry.py", line 616, in _get_valid_format
    "{0}".format(format_table_str))
astropy.io.registry.IORegistryError: Format could not be identified.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No           
               ascii.aastex  Yes   Yes            No           
                ascii.basic  Yes   Yes            No           
                  ascii.cds  Yes    No            No           
     ascii.commented_header  Yes   Yes            No           
                  ascii.csv  Yes   Yes            No           
              ascii.daophot  Yes    No            No           
                 ascii.ecsv  Yes   Yes            No           
           ascii.fast_basic  Yes   Yes            No           
ascii.fast_commented_header  Yes   Yes            No           
             ascii.fast_csv  Yes   Yes            No           
       ascii.fast_no_header  Yes   Yes            No           
             ascii.fast_rdb  Yes   Yes            No           
             ascii.fast_tab  Yes   Yes            No           
          ascii.fixed_width  Yes   Yes            No           
ascii.fixed_width_no_header  Yes   Yes            No           
 ascii.fixed_width_two_line  Yes   Yes            No           
                 ascii.html  Yes   Yes           Yes           
                 ascii.ipac  Yes   Yes            No           
                ascii.latex  Yes   Yes           Yes           
            ascii.no_header  Yes   Yes            No           
                  ascii.rdb  Yes   Yes           Yes           
                  ascii.rst  Yes   Yes            No           
           ascii.sextractor  Yes    No            No           
                  ascii.tab  Yes   Yes            No           
                       fits  Yes   Yes           Yes           
                       hdf5  Yes   Yes           Yes           
                    votable  Yes   Yes           Yes           
                     aastex  Yes   Yes            No        Yes
                        cds  Yes    No            No        Yes
                        csv  Yes   Yes           Yes        Yes
                    daophot  Yes    No            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
Makefile:116: recipe for target 'GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_xm.fits' failed
make: *** [GRB180805A/28s_images/regrid_1217495184-28s-t0000-pbcorr-I_xm.fits] Error 1
```

**Comment by PaulHancock** [comment]
Most likely this is because some of the `_comp.fits` and/or `_xm.fits` files are actually empty.
This can be because turning OFF the warping causes empty files to be touched in order to get make to play nice. If you then turn ON the warping you have to delete these empty files.

I recommend doing:
`find . -iname '*_comp.fits' -size 0 -delete`
and
`find . -iname '*_xm.fits' -size 0 -delete`
to remove the files. I usually exclude the `-delete` command the first time I run this just to make sure that it's not going to delete files I want to keep.

**Comment by gemmaanderson** [comment]
I am starting from scratch with fits_warp switched on, so I don't have any zero-sized files. I therefore dont think this is the problem.

**Comment by PaulHancock** [comment]
This is for the `make` version of Robbie which is no longer supported so i'm not going to address this issue.
